CREATE TABLE IF NOT EXISTS employee_offers (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id uuid REFERENCES hrms_employees(id) ON DELETE CASCADE,
    candidate_name text NOT NULL,
    candidate_email text NOT NULL,
    candidate_address text,
    designation text,
    department text,
    offer_type text,
    effective_date date,
    ctc_annual numeric(12,2),
    basic_monthly numeric(12,2),
    hra_monthly numeric(12,2),
    special_allowance_monthly numeric(12,2),
    pf_monthly numeric(12,2),
    bonus_monthly numeric(12,2),
    contract_end_date date,
    commission_min numeric(12,2),
    commission_max numeric(12,2),
    stipend_monthly numeric(12,2),
    duration_months integer,
    responsibilities text,
    content_html text,
    status text,
    created_by text,
    admin_comments text,
    sign_token text,
    sign_token_expires_at timestamp with time zone,
    signed_name text,
    signed_ip text,
    signed_at timestamp with time zone,
    countersigned_at timestamp with time zone,
    countersigned_by text,
    final_pdf_url text,
    submitted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS employee_ndas (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    offer_id uuid REFERENCES employee_offers(id) ON DELETE CASCADE,
    employee_id uuid REFERENCES hrms_employees(id),
    content_html text,
    status text,
    sign_token text,
    sign_token_expires_at timestamp with time zone,
    sent_at timestamp with time zone,
    signed_at timestamp with time zone,
    signed_name text,
    signed_ip text,
    countersigned_at timestamp with time zone,
    countersigned_by text,
    final_pdf_url text,
    created_at timestamp with time zone DEFAULT now()
);
